version: '3.7'

services:
 web:
  build:
    context: .
  ports:
     - 5000:5000
  volumes:
     - ./:/app
  container_name: web

 mysqldb:
   image: mysql:5.7
   ports:
     - 3306:3306
   environment:
     - MYSQL_ROOT_PASSWORD=secret
   volumes:
     - mysql:/var/lib/mysql
     - mysql_config:/etc/mysql
   container_name: mysql

volumes:
  mysql:
  mysql_config:
